#!/bin/sh

clear
echo "  "
echo "  "
echo " L D M A P        "   
echo "Construction of linkage disequilibrium maps from diplotype data..."
echo " VERSION 2.0 November 2014  "
MODE=0
while [ $MODE -ge -1 -a $MODE -lt 2  ]
do
echo "  "
echo "  "
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Enter number to select function "

echo "    1             Construct LD map in segments from intermediate file  "

echo "    2             quit      "

echo "  "


read MODE

while [ $MODE -ge 1 -a $MODE -lt 2 ]
do
        
        if [ $MODE -eq 1 ]
        then
        echo  "*Construct an LDU map*" 
        echo "  " 
	echo  "Input data file is: "
	read DATA
	echo  "Intermediate file is: "
	read INT
        echo  "Job file is: "
	read JOB
	echo  "Map (output) file is: "
	read TERSE
	echo  "Long output file is: "
	read PROLIX
	echo  "MAF cut-off (eg. 0.05) is: "
	read MAF 
	echo  "HWE P-value cut-off (eg. 0.001) is: "
	read HWE 
        echo  "Script file (to run the program) is: "
	read CP
	rm -f $CP
        echo "Writing an executable script file........"
        echo "ldmapper1" $DATA $INT $JOB $TERSE $PROLIX $MAF $HWE >> $CP
        chmod +x $CP
        echo "Run this job (y/n) ?"
        read run
        case $run in y) /bin/sh $CP ;;
        esac 
        MODE=0 
        fi
        
done
done
